### ISSUE TITLE
Snowflake: snowsql not found in docker image on MacOS

### ISSUE THREAD

**Issue by BorisPerevalov** [sqitchers/docker-sqitch#15]
Docker image I've built on Mac OS (10.14.5) doesn't work. I can use sqitch status command, but not any command that applies changes (deploy, revert). I've this error:
"/Applications/SnowSQL.app/Contents/MacOS/snowsql" failed to start: "No such file or directory"

**Comment by theory** [comment]
Sounds like you have `engine.snowflake.client` set in your `~/.sqitch/sqitch.conf` file. The `sqitch-docker.sh` script mounts your home directory, so Sqitch inside the image will read your config there. You don't want Mac-specific config in there when running the Docker image.

**Comment by BorisPerevalov** [comment]
Exactly! Thank you. I close this issue.
