### ISSUE TITLE
Use of uninitialized value $gid in getgrgid

### ISSUE THREAD

**Issue by agdespopoulos** [sqitchers/docker-sqitch#17]
Version 1.0.0
Ubuntu 18.04.02
Using docker-sqitch.sh (https://github.com/sqitchers/docker-sqitch/commit/58a5c32473c711bb9da1ade025a4eb3124ddb8b3)

When running commands that perform certain actions on the database, I see a warning about "Use of uninitialized value $gid in getgrgid at /usr/share/perl5/PgCommon.pm line 783.". It doesn't seem to impact the operation of Sqitch at all, but it is noisy and annoying, and I'm not sure why it's happening.

Running the script with `sudo` resolves the problem, but I don't have any other problems with things like Sqitch not being able to create files and directories when not running with `sudo`, just this warning.

Possibly similar to sqitchers/sqitch#459? I tried the debugging steps there and nothing helped. Here's some more info that might hopefully help?

getent output:

```
backend/db » user=${USER-$(whoami)}; getent passwd "$user"       
adespopoulos:x:1001:1001:Ag Despopoulos,,,:/home/adespopoulos:/usr/bin/zsh
```

Added an echo to docker-sqitch.sh to print all the environment variables it passes to the docker container:

```
SQITCH_ORIG_SYSUSER=adespopoulos -e SQITCH_ORIG_EMAIL=adespopoulos@pooter -e TZ=EDT -e LESS=-R -e SQITCH_ORIG_FULLNAME=Ag Despopoulos -u 1001:1001 -e HOME=/home
```

Example:

```
backend/db » sqitch --version
sqitch (App::Sqitch) v1.0.0

backend/db » sqitch revert HEAD^
Revert changes to appschema from local? [Yes]
  - inspection .. Use of uninitialized value $gid in getgrgid at /usr/share/perl5/PgCommon.pm line 783.
ok

backend/db » sqitch verify
Verifying local
  * appschema .. Use of uninitialized value $gid in getgrgid at /usr/share/perl5/PgCommon.pm line 783.
ok
Undeployed change:
  * inspection
Verify successful

backend/db » sqitch deploy
Deploying changes to local
  + inspection .. Use of uninitialized value $gid in getgrgid at /usr/share/perl5/PgCommon.pm line 783.
Use of uninitialized value $gid in getgrgid at /usr/share/perl5/PgCommon.pm line 783.
ok
``

**Comment by theory** [comment]
I made a new docker image today based on Debian buster, and it no longer seems to exhibit this warning. Here's what I get with `sqitch/sqitch:0.9999`:

```
SQITCH_IMAGE=sqitch/sqitch:0.9999 ../sqitch deploy db:pg://sqitch:devonly@pdxdvpg01.iovationnp.com/dwheeler
Deploying changes to db:pg://sqitch:@pdxdvpg01.iovationnp.com/dwheeler
  + foo .. Use of uninitialized value $gid in getgrgid at /usr/share/perl5/PgCommon.pm line 783.
ok
```

But with the 1.0.0 image made today:

```
../sqitch deploy db:pg://sqitch:devonly@pdxdvpg01.iovationnp.com/dwheeler
Deploying changes to db:pg://sqitch:@pdxdvpg01.iovationnp.com/dwheeler
  + foo .. ok
```

No more warning. I guess @df7cb made a change to PgCommon at some point to eliminate this warning?

**Comment by df7cb** [comment]
I can't remember any change in that area, but if it works now... let me know if there's anything I need to fix.

**Comment by agdespopoulos** [comment]
Yep, whatever the change was, this is fixed for me now. The issue is gone with the latest Docker Hub images. I'm glad my whole thing of creating the user isn't necessary. :)

Thanks for the help!

**Comment by theory** [comment]
@df7cb Yeah, I’m not sure what changed, but the issue definitely went away. I believe you can still see it if you build an image on Debian 9 (I use Debian-slim) and connect to the image using the docker host UID and GID, which don’t exist inside the container, and then run whatever Postgres thing triggers PgCommon.

I’m not even clear on the purpose of PgCommon or when it runs. Does it get triggered by `psql`? Perl Postgres apps? Something else? I assume that Postgres on Debian would work fine without it; true?

**Comment by df7cb** [comment]
psql is invoked through /usr/share/postgresql-common/pg_wrapper which uses PgCommon.pm.

**Comment by theory** [comment]
Ah, okay. What’s psql missing that requires it?

**Comment by df7cb** [comment]
Cluster integration with postgresql-common, `psql --cluster 11/main`. See `pg_wrapper(1)`.

https://manpages.debian.org/buster/postgresql-client-common/pg_wrapper.1.en.html

**Comment by theory** [comment]
Doesn't seem necessary just to use `psql` to connect to a database running elsewhere, no? If not, what's the simplest way to remove it? Just link to the proper version of `psql` from `/usr/local`?

**Comment by df7cb** [comment]
I'm not sure which problem you are trying to fix here?

**Comment by theory** [comment]
I would like to remove PgCommon as a vector for issues. It occasionally emits warnings that confuse users (and me) because it’s not really visible. Sqitch just needs plain old `psql` and nothing special.

**Comment by df7cb** [comment]
If it's causing issues, please file a bug. If you try to hack around the way PostgreSQL works on Debian, it's likely to cause more issues on another level.

**Comment by theory** [comment]
Don't need PostgreSQL, just `psql`. Is there something lacking about the regular `psql` client?
