### ISSUE TITLE
No LICENSE found

### ISSUE THREAD

**Issue by waterkip** [sqitchers/docker-sqitch#18]
Hello, I'm looking at some of the code and I want to change docker-sqitch to incorporate into our toolset which uses docker-compose. I cannot find a LICENSE file in this project, so I cannot change/adapt the code without breaking some copyright law.

Could you add a LICENSE to make changing and modifying the code possible?

Many thanks!

**Comment by theory** [comment]
I guess it ought to go under the same license as [Sqitch](/sqitchers/sqitch/blob/develop/LICENSE.md).

**Comment by clad** [comment]
Yes, please add a LICENSE file.
