### ISSUE TITLE
sqitch looks for .pgpass in /root instead of /home

### ISSUE THREAD

**Issue by nugget** [sqitchers/docker-sqitch#2]
## Environment

* image sqitch/sqitch:latest
* Docker for Mac on macOS 10.14

## Summary

When running docker-ized sqitch against `db:pg:` targets, sqitch is unable to pull credentials from the `.pgpass` file mounted in `/home`.  Sqitch aborts with the message `fe_sendauth: no password supplied`.

Sqitch ignores the value of the `$HOME` environment variable and instead relies on root's passwd entry to locate the `.pgpass`file.

## Symptoms

Overriding the entrypoint in the image and running `/bin/dash` exhibits the same behavior.  Trying to use sqitch pointing to a postgresql target behaves the same way.

```
root@linuxkit-025000000001:/repo# sqitch status targetname
# On database targetname
fe_sendauth: no password supplied
```

The target is configured as:
```
[target "targetname"]
    uri = db:pg://dbuser@dbhost.example.com/dbname
```

Curiously, the pg tools in the image have the same problem

```
root@linuxkit-025000000001:/repo# psql --Udbuser -h dbhost.example.com dbname
Password for user dbuser:
```

## Workaround

* If I copy the `.pgpass` file from `/home` to `/root` it works.
* Alternately, If I change the home directory for root in `/etc/passwd` to `/home` that also works.
* I have verified that the HOME environment variable is set to `/home` as expected and this appears to have no effect.

**Comment by nugget** [comment]
## Proposed solution

Changing the mountpoint for home in `docker-sqitch.sh` fixes the glitch.

```
docker run -it --rm --network host \
    --mount "type=bind,src=$(pwd),dst=/repo" \
    --mount "type=bind,src=$HOME,dst=/root" \
    "${passenv[@]}" "$SQITCH_IMAGE" "$@"
```

**Comment by theory** [comment]
#3 seems like a no-brainer. Thank you.

**Comment by theory** [comment]
BTW, as of 984e4f5, I've changed it to create a user named `sqitch`, using `/home` for the home directory. LMK if that causes any problems for you.

**Comment by nugget** [comment]
Confirmed working with the latest image/changes.  Thanks!
