### ISSUE TITLE
Exasol DBD::ODBC 1.59 required to manage Exasol

### ISSUE THREAD

**Issue by Nicqu** [sqitchers/docker-sqitch#22]
Hi,
This error occurs when I try to deploy changes to an Exasol database.
```
./sqitch deploy
DBD::ODBC 1.59 required to manage Exasol
```

It seems that sqitch cannot find the odbc driver even if it is installed in the docker image.

Steps to reproduce the error:
```
mkdir Schema_test && cd Schema_test
./../sqitch init Schema_test --uri https://github.com/sqitchers/sqitch-exasol-intro/ --engine exasol
./../sqitch config --user engine.exasol.client /opt/EXAplus-6.2.3/exaplus
./../sqitch config --user user.name 'Sqitch-Exasol on Docker'
./../sqitch add appschema -n 'Add schema for all Schema_test objects.'
./../sqitch deploy 'db:exasol://USER:PASS@IP:8563/?Driver=Exasol'
DBD::ODBC 1.59 required to manage Exasol
```

**Comment by theory** [comment]
Please see #21. I'll add notes to the Exasol and Vertica READMEs.

**Comment by Nicqu** [comment]
unfortunately, that didn't help much. I'm getting this error now: 
`[unixODBC][Driver Manager]Data source name not found, and no default driver specified (SQL-IM002)`

I couldn't find a solution in https://github.com/sqitchers/docker-sqitch/pull/16

**Comment by Nicqu** [comment]
Holy moly.. I found the problem. 
The password contains a `#` which led to the problem: dsn not found.

**Comment by theory** [comment]
LOL, ODBC is kind of terrible. :-(
