### ISSUE TITLE
Sqitch Snowflake deployment failing

### ISSUE THREAD

**Issue by bcgpartners** [sqitchers/docker-sqitch#24]
I am using Sqitch Snowflake Docker image sqitch/sqitch:1.0.0-snowflake . I can conntect to the database without any issues. However, when I run the following

`./sqitch deploy`
It just stays at the following forever.

`Adding registry tables to test_db`
I have checked the logs at snowflake side in information_schema.query_history() table and it is failing at the following

```
USE SCHEMA sqitch
SQL compilation error:
Object does not exist, or operation cannot be performed.
```
It seems that even when pointed to an empty database, Sqitch is assuming that the SQITCH schema already exists.

**Comment by theory** [comment]
Great find, thanks! I added it in 9b4ca48.
