### ISSUE TITLE
DBD::ODBC 1.59 required to manage Snowflake

### ISSUE THREAD

**Issue by mdhatrika** [sqitchers/docker-sqitch#26]
Hi,
I am planning to integrate sqitch as part of the CICD Pipeline, for this to happen I want to first set the sqitch locally to connect to snowflake. As part of the prerequisites, I use these 2 documents

To download the odbc driver for snowflake I followed this document and made setup and was able to connect to the snowflake successfully and following is the version it shows
SQL> select current_client();
CURRENT_CLIENT()
| ODBC 2.21.3
https://support.snowflake.net/s/article/How-to-create-Snowflake-ODBC-DSN-On-MacOS
Downloaded and installed the snowsql using this document and was able to connect to snowflake succesfully
https://docs.snowflake.com/en/user-guide/snowsql-install-config.html#installing-snowsql-on-macos-using-the-installer
For sqitch I refred to this document https://sqitch.org/docs/manual/sqitchtutorial-snowflake/
So the problem is when I try to do sqitch deploy I am getting this error
DBD::ODBC 1.59 required to manage Snowflake
**sqitch deploy 'db:snowflake://account_name/DBname?Driver=SnowflakeDSIIDriver'**
I tried including the username and password in the above URI but still getting the same error.
Please help me to figure out what I am doing wrong. Thanks

**Comment by theory** [comment]
You also need to install DBD::ODBC. I don’t know how you installed Perl and all the Sqitch dependencies, but you’ll need to install DBD::ODBC such that it can find the ODBC libraries when it builds.

**Comment by mdhatrika** [comment]
after I install the DBD:: ODBC  and DBI it is working now. Thank you so much :)

**Comment by RutujaMGholap** [comment]
I am facing the same problem
I tried installing it by command cpanm DBD::ODBC
But I get following result:
cpanm (App::cpanminus) 1.9018 on perl 5.032000 built for darwin-thread-multi-2level
Work directory is /Users/rgholap/.cpanm/work/1611137520.38841
You have make /usr/bin/make
You have /usr/bin/curl: curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
You have /usr/bin/tar: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
You have /usr/bin/unzip
Searching DBD::ODBC () on cpanmetadb ...
--> Working on DBD::ODBC
Fetching http://www.cpan.org/authors/id/M/MJ/MJEVANS/DBD-ODBC-1.61.tar.gz
-> OK
Unpacking DBD-ODBC-1.61.tar.gz
Entering DBD-ODBC-1.61
Checking configure dependencies from META.yml
Checking if you have DBI 1.21 ... Yes (1.643)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.44)
Configuring DBD-ODBC-1.61
Running Makefile.PL

**********
	Remember to actually *READ* the README file!
	And re-read it if you have any problems.

**********

OSNAME: darwin
LANG: 
ODBCHOME: /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib:
LD_LIBRARY_PATH: 
DBROOT: 
WINDIR: 
II_SYSTEM: 
DBD_ODBC_UNICODE: 
Perl: 5.032000
ExtUtils::MakeMaker: 7.44
Command line options:
  u! = undef
  x! = undef
  o=s = 
  g! = 0
  w! = undef
  e! = undef

You are using a Perl configured with threading enabled.
Please read the warnings in DBI about this.

You should also be aware that on non-Windows platforms ODBC drivers come
in two forms, thread-safe and non-thread-safe drivers and you may need
to make sure you are using the right one.

Press return to continue...  
Looking for odbc_config in : /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib:
Looking for odbc_config at /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib:/bin/odbc_config
Looking for odbc_config in (PATH) /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  odbc_config not found
Looking for iodbc-config in PATH /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  iodbc_config not found
odbc_config not found - ok, there are other things I can do
Still trying to guess ODBCHOME - looking for headers now
  trying /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib:/include
  trying /usr/include
  trying /usr/local/include
  trying /usr/pkg/include
  trying /usr/local/easysoft/unixODBC/include

I cannot find driver manager header files. Perhaps you need to install the
unixodbc-dev package or the iodbc-dev package


The DBD::ODBC module needs to link with an ODBC 'Driver Manager'.
(The Driver Manager, in turn, needs one or more database specific ODBC
drivers. The DBD::ODBC module does _not_ include any ODBC drivers!)

You need to indicate where your ODBC Driver Manager is installed.
You can do this by:

o setting the ODBCHOME environment variable
o running 'perl Makefile.PL -o odbcdir'
o adding path to odbc_config/iodbc_config to PATH

If you do not have an ODBC Driver Manager you should try to get hold of
the unixODBC packages for your system or build it from source (see
http://www.unixodbc.org). If you install driver manager packages you
need to include the "XXX-dev" package which includes the C header files.
-> N/A
-> FAIL No MYMETA file is found after configure. Your toolchain is too old?
-> FAIL Configure failed for DBD-ODBC-1.61. See /Users/rgholap/.cpanm/work/1611137520.38841/build.log for details.




Please help me overcoming it, and I have ODBC driver and iodbc set up well

**Comment by binbenban** [comment]
> after I install the DBD:: ODBC and DBI it is working now. Thank you so much :)

could you please share the steps to install these? Thanks!

**Comment by jimdobson-act3** [comment]
@mdhatrika, I'm experiencing the same problem, would be very helpful if you would share the steps to install. Thank you!

**Comment by rubenslj00** [comment]
I need help on how to install DBD::ODBC 1.59 , and how to configure it please
