### ISSUE TITLE
main branch rename broke git.io link

### ISSUE THREAD

**Issue by harryparkdotio** [sqitchers/docker-sqitch#28]
the git.io link (https://git.io/fAX6Z) which redirects to the `docker-sqitch.sh` file in the root of the repository, expects a `master` branch.

the renaming of `master` to `main` broke the git.io link.

**Comment by theory** [comment]
Oy vey, should have thought of that. I can create a new git.io link and updated all references, but first have submitted a support request to GitHub to see if they can just update the record in their database.

Thanks for pointing this out, @harryparkdotio.

**Comment by theory** [comment]
New URL is https://git.io/JJKCn

**Comment by theory** [comment]
Updated the READMEs and Docker Hub. Will have to think about whether to bother with the old version branches.

**Comment by theory** [comment]
Updated the v1.0.0 branch and pushed a new build; also updated v0.9999 and v0.9998, but the builds fail, and I don't think it's worth fixing (which would require cherry-picking a bunch of old changes from main).
