### ISSUE TITLE
sqitch script not setting environment variables.

### ISSUE THREAD

**Issue by venkatra** [sqitchers/docker-sqitch#35]
Currently in the script : ** [docker-sqitch.sh](https://git.io/JJKCn) ** ; You are iterating the various engine specific environment variables and passing to the docker. 

`bash
    do
    if [ -n "${!var}" ]; then
       passopt+=(-e $var)
    fi
done
`
However when the script runs, in my case i was using Snowflake, it does not set the actual value. This is the debug output:

`
      + docker run -it --rm --network host 
    --mount type=bind,src=/Users/learner/sqit/RAW/SALES,dst=/repo 
   ... (cut of for clarity) ...
    -e SQITCH_ORIG_SYSUSER=developer -e SQITCH_ORIG_EMAIL=XXX@devlaptop 
    -e SNOWSQL_ACCOUNT -e SNOWSQL_USER -e SNOWSQL_PWD -e SNOWSQL_DATABASE 
    -e SNOWSQL_REGION -e SNOWSQL_WAREHOUSE 
    -e HOME=/home sqitch/sqitch:snowflake 
    deploy --db-name DEV -f ./sqitch.plan
`

Notice that the value for **-e SNOWSQL_ACCOUNT -e SNOWSQL_USER** etc.. are not set.

I made some update in the script as below 

`bash
     do
     if [ -n "${!var}" ]; then
          var_val=`printf '%s\n' "${!var}"`
          passopt+=(-e "$var=${var_val}")
    fi
  done
`

Notice **var_val=`printf '%s\n' "${!var}"`;passopt+=(-e "$var=${var_val}")**
fixed the issue. Now the same script pass the env to the docker:

`bash
   + docker run -it --rm --network host 
  ... (cut of for clarity) ...
  -e SNOWSQL_ACCOUNT=venkat 
  -e SNOWSQL_USER=JARJAR 
  -e SNOWSQL_PWD=BEEPBOP
  ... (cut of for clarity) ...
`

Hope this can be adderesed in future release

**Comment by theory** [comment]
> Notice that the value for -e SNOWSQL_ACCOUNT -e SNOWSQL_USER etc.. are not set.

Yeah, it doesn't have to. The `docker run` [`--env docs`](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) say:

> You can also use variables that you’ve exported to your local environment:
>
> ```
> export VAR1=value1
> export VAR2=value2
>
> $ docker run --env VAR1 --env VAR2 ubuntu env | grep VAR
> VAR1=value1
> VAR2=value2
>```

So it's not necessary to copy the values.
