### ISSUE TITLE
Sqitch does not work after homebrew upgrade (Mac OS X)

### ISSUE THREAD

**Issue by tiguchi** [sqitchers/docker-sqitch#38]
# Problem

When Perl is updated via `brew upgrade`, sqitch usually stops working with an error message as follows:

```
/usr/local/bin/sqitch: /usr/local/Cellar/perl/5.32.1/bin/perl: bad interpreter: No such file or directory
```

# Reproduction Steps

For Mac OS X

1. Install sqitch via `brew install sqitch`
2. Upgrade Perl via `brew upgrade`
3. Run `sqitch`

# Workaround

The only fix to my knowledge is reinstalling sqitch via `brew reinstall sqitch`.

# Troubleshooting

I guess this is caused by sqitch referencing the previous Perl binary before the upgrade.

Homebrew unfortunately installs minor and patch version updates in new directories, causing problems like this also for other applications.

I'm not sure if this is entirely a homebrew defect or whether there is something that could be done right in the sqitch launcher script or the Homebrew installation script. Maybe there is an upgrade hook for Homebrew packages that could be used for relinking with the correct Perl installation.

Maybe there is also a better way for finding the correct Perl binary such as:

```
#!/usr/bin/env perl
```

**Comment by theory** [comment]
If we switched it to use `#!/usr/bin/env/perl`, I wonder if it would then fail spectacularly on a major version upgrade that breaks binary compatibility. Would be better if there was a major-version-specific symlink to rely on or something.

**Comment by tiguchi** [comment]
I just found the following Homebrew ticket, and it looks like pre- and post-install hooks are not a wanted feature: https://github.com/Homebrew/brew/issues/2202

It seems Homebrew does symlink the latest installed versions of all packages in the following base directory:

```
/usr/local/var/homebrew/linked/
```

My local installation contains a `perl` directory with its `bin`, `lib` and `share` sub-directories. No version number in that file path. This doesn't guard against the binary compatibility problem you mention. What would be the worst that could happen in that case? Would sqitch just crash or produce an error message?

**Comment by theory** [comment]
Yes, probably. But it would happen to folks once a year at most (at major version releases).

**Comment by bhawnatyagi** [comment]
I am facing the same issue after homebrew upgrade (Mac OS X). I can see this issue is in open status but is there any way to fix this issue? This is a blocker for our production deployment. I tried reinstalling sqitch and currently I have sqitch v1.3.1 on my mac.

**Comment by theory** [comment]
Have you tried removing and re-installing Sqitch?

**Comment by theory** [comment]
I have updated my Mac, so tried to run Sqitch, and yeah, it failed due to an upgraded Perl. Reinstall didn't fix it, but removing it then installing it again fixed it.

```
brew remove sqitch
brew install sqitch --with-postgres-support --with-sqlite-support
```

I don't think there is anything to do about this: when there is a major Perl upgrade, none of the modules can be considered binary compatible, so Sqitch must be completely reinstalled.

**Comment by bhawnatyagi** [comment]
I need the reinstallation for snowflake. Does the below command look right to you? 
 brew install sqitch --with snowflake-support?

**Comment by theory** [comment]
Yep, [documented here](/sqitchers/homebrew-sqitch#--with-snowflake-support)

**Comment by bhawnatyagi** [comment]
Hi, I am getting below error while running sqitch status command. Its complaining about tag that has been used to tag one of the change. 

sqitch status 'db:snowflake://username:password@account.snowflakecomputing.com/db?Driver=Snowflake;warehouse=wh'
Syntax error in sqitch.plan at line 111: Tag "public/procedures/alter_datalake_to_prelanding_insert" contains illegal character /

Could you please help in resolving this issue? What does this error mean?

**Comment by bhawnatyagi** [comment]
Thanks, I will do some testing with the provided steps. We are also trying to do deployment using sqitch docker using linux. However, we are getting below error when we tried using sqitch status :
output=Database db:snowflake://<account-name>/<db_name>?Driver=Snowflake;warehouse=<wh>;pwd=<pwd>;UID=<user>;role=<Role> has not been initialized for Sqitch. What does this error mean?

**Comment by theory** [comment]
It means you haven't deployed a change to that database before, so it does not yet have a registry schema.

**Comment by bhawnatyagi** [comment]
Oh but we have deployed changes to this database before. The database that we are using is production database. Any idea what could be wrong or how can I debug this issue?

**Comment by theory** [comment]
My guess is you're not connecting to the database you think you are, or else that the user or role you're using does not have the necessary access.

**Comment by pchilds** [comment]
Why is this considered completed? Instead of making breaking changes every major version upgrade it is currently still breaking every version upgrade.

**Comment by theory** [comment]
Mainly because this repository is for the Docker image, not the Homebrew formula. Does sqitchers/homebrew-sqitch#61 correspond to the problem you're seeing?
