### ISSUE TITLE
debian:stalble-slim doesn't allow apt-get commands

### ISSUE THREAD

**Issue by BoochParadise** [sqitchers/docker-sqitch#42]
https://github.com/debuerreotype/docker-debian-artifacts/issues/134
debian:stable-slim uses unavailable apt security repository #134

The issue was fixed but I think sqitch/sqitch:latest needs to be rebuilt.

**Comment by theory** [comment]
I just updated for Debian Sid in ac30979  and pushed it; the new build is on Docker Hub now. Will make sure Snowflake and Exasol build properly
