### ISSUE TITLE
Permission error when running Snowflake image under Linux

### ISSUE THREAD

**Issue by peter-wimsey** [sqitchers/docker-sqitch#49]
When running docker-sqitch.sh I get

```
$ sqitch deploy
Deploying changes to database
  + change .. [Errno 13] Permission denied: '/var/.snowsql'
```
Not the same for all commands, `log` and `status` work, `deploy` and `revert` do not.

I believe this is related to cd14783c71 - my current Linux user has permissions to the mounted files in `/repo` but not to `/var/.snowsql`.

Adding the following line

```
RUN chmod --recursive a+rx /var/.snowsql
```

at https://github.com/sqitchers/docker-sqitch/blob/v1.3.1.0/snowflake/Dockerfile#L55 seems to fix the issue.

**Comment by theory** [comment]
Nice find, thank you!
