### ISSUE TITLE
Question: In development, I run my Postgres database inside a docker container using their official docker image...

### ISSUE THREAD

**Issue by johncmunson** [sqitchers/docker-sqitch#5]
In development, I run my Postgres database inside a docker container using their official docker image, and I interact with the database from a separate dockerized NodeJS application. Both containers are booted through the use of docker-compose.

In this case, what would be the proper way for getting up and running with sqitch? Should I somehow utilize the sqitch docker image and throw a third container into the mix? Or do I need to add sqitch as a dependency to either the Node image or the Postgres image?

**Comment by theory** [comment]
I personally would use the Sqitch Docker image, yes, but really it depends on what your requirements are, and I don't know all the options and parameters. I suggest you post to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) for broader input to your question.
