### ISSUE TITLE
Sqitch docker file build errors in mariadb-client-core version

### ISSUE THREAD

**Issue by PrakashSelvarajS** [sqitchers/docker-sqitch#54]
Hi,  
We have been using the Sqitch docker file in the github repo: https://github.com/sqitchers/docker-sqitch/blob/main/Dockerfile
It had been working well, but from yesterday we get a Sqitch docker build failure with error as below:

libperl error initially:
------------------------

#5 4.071 E: Unable to locate package libperl5.32
#5 4.071 E: Couldn't find any package by glob 'libperl5.32'
#5 4.071 E: Couldn't find any package by regex 'libperl5.32'

then on upgrade to libperl5.36, it errors in the mariadb-client-core version:
-----------------------------------------------------------------------------

E: Package 'mariadb-client-core-10.5' has no installation candidate

We are unable to find the correct 'mariadb-client-core' version to fix the above error. 
It appears the debian images has gone for an update yesterday that could have caused the error.

Would you able to help us fix this please?

Thank you

Regards
Prakash Selvaraj

**Comment by theory** [comment]
Will be fixed by #55.
