### ISSUE TITLE
sqitch image latest seems corrupt

### ISSUE THREAD

**Issue by acl-oss** [sqitchers/docker-sqitch#59]
We are seeing within our Artifactory remote repo that connects to "registry-1.docker.io" that when trying to pull down the latest sqitch from our Artifactory it is picking sha256__9a5adca92487848484a46e2a34150b960b545bc4ea7dd9ddfbd00a1705ad4a59 with a size stating 338.24 KB in the GUI. If we check within the manifest it states a different size:

            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:9a5adca92487848484a46e2a34150b960b545bc4ea7dd9ddfbd00a1705ad4a59",
            "size": 11469372

This doesn't seem correct and the size should match somewhere near to each other going by other images.

**Comment by theory** [comment]
I don't know what that's about, but the latest from two days ago is [acd47c19ba4c](https://hub.docker.com/layers/sqitch/sqitch/latest/images/sha256-acd47c19ba4cb1005eaeb17500c6236d462559dc7b2acfdf68d955adb72ed122) for linux/amd64 at 65.7 MB and [d3cc0aa6bc2b](https://hub.docker.com/layers/sqitch/sqitch/v1.4.0.2/images/sha256-d3cc0aa6bc2b0ae4a2f289bbe3f16d0a77eb1edda326d923696c7974cde290bb?context=explore) for linux/arm64 at 63.55 MB.
