### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

### ISSUE THREAD

**Issue by franciscohanna92** [sqitchers/docker-sqitch#9]
_This issue was originally solved [here](https://github.com/sqitchers/sqitch/issues/458). I'm adding it here to keep track of it in this repo._

So, I was trying to use Sqitch from the [docker image](https://hub.docker.com/r/sqitch/sqitch/) using the bash script provided there. My MySQL was running on my localhost. When I tried to use sqitch, it said:

> Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

What I did to solve it was to locate the `mysqld.sock` in my localhost, and mounting the folder that contained (/run/mysqld) it in the container's `/var/run/mysqld` folder, adding the following parameter to docker run:

`--mount "type=bind,src=/run/mysqld,dst=/var/run/mysqld"`

The docker run command ended up as:

```
docker run -it --rm --net="host" \
    --mount "type=bind,src=/run/mysqld,dst=/var/run/mysqld" \
    --mount "type=bind,src=$(pwd),dst=/repo" \
    --mount "type=bind,src=$HOME,dst=$homedst" \
    "${passopt[@]}" "$SQITCH_IMAGE" "$@"
```

**Comment by theory** [comment]
Consider adding documentation to the README or the Docker Hub page listing ways to connect to database servers on the hosting machine from inside the container.

**Comment by theory** [comment]
See notes on #10 for the reason the notes in 66b22b3 are preferred.
